version: "3"
services:

   db:
     image: postgres:9.6
     restart: always
     environment:
       POSTGRES_PASSWORD: projetoIHC
       POSTGRES_DB: projetoIHC
     ports:
       - 5436:5432
     volumes:
       - ./postgres-data:/bitnami/postgresql/data
